version: "3.8"

services:
  website:
    build:
      context: ./website
      dockerfile: dev.Dockerfile

    env_file:
      - db/.env

    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./website:/lazy_in_it/website

  db:
    expose:
      - "5432:5432"
    build:
      context: ./db
      dockerfile: dev.Dockerfile

    volumes:
      - db_data:/var/lib/postgresql/data

    env_file:
      - db/.env

volumes:
  db_data:
